{ config, lib, pkgs, ... }:
let
  cfg = config.custom.user.shell;
  configDir = ../../config;
in {
  options.custom.user.shell = {
    enable = lib.mkEnableOption "shell configuration (fish, zsh, nushell)";
  };

  config = lib.mkIf cfg.enable {
    # Fish as the default shell (Req 11.1, 11.4)
    programs.fish = {
      enable = true;
    };

    # Zsh available as alternative shell (Req 11.2)
    programs.zsh = {
      enable = true;
    };

    # Nushell available as alternative shell (Req 11.2)
    programs.nushell = {
      enable = true;
    };

    # Starship prompt for fish (Req 11.3)
    programs.starship = {
      enable = true;
      enableFishIntegration = true;
    };

    # Direnv shell integration for fish, zsh, and nushell (Req 16.6)
    programs.direnv = {
      enable = true;
      nix-direnv.enable = true;
      enableBashIntegration = true;
    };

    # Per-shell Config_Source files (Req 11.5)
    # Fish configuration from config/fish/
    # mkForce overrides the config generated by programs.fish.enable
    xdg.configFile."fish/config.fish" = lib.mkIf (builtins.pathExists (configDir + "/fish/config.fish")) (lib.mkForce {
      source = configDir + "/fish/config.fish";
    });

    # Zsh configuration from config/zsh/
    home.file.".zshrc" = lib.mkIf (builtins.pathExists (configDir + "/zsh/.zshrc")) {
      source = configDir + "/zsh/.zshrc";
    };

    # Nushell configuration from config/nushell/
    xdg.configFile."nushell/config.nu" = lib.mkIf (builtins.pathExists (configDir + "/nushell/config.nu")) {
      source = configDir + "/nushell/config.nu";
    };
  };
}
