#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

REPO_URL="https://github.com/iron-tower-dev/nixos-configuration.git"
HOST="${HOST:-mast}"
REPO_DIR="${REPO_DIR:-$HOME/nixos-configuration}"

banner "Install NixOS on ${HOST}"

# ── Stage 1: preflight ──────────────────────────────────────────────────────
stage "Preflight"
say "Confirming we're actually inside a NixOS live installer, not some other shell."
if [[ ! -e /etc/NIXOS ]] || ! command -v nixos-install >/dev/null 2>&1; then
  warn "This doesn't look like a NixOS live environment (/etc/NIXOS or nixos-install missing)."
  say  "Boot ${HOST} from a NixOS installer USB, connect to the network"
  say  "(nmtui for wifi, or plug in ethernet), then re-run this script from there."
  exit 1
fi
note "✓ running inside a NixOS live environment"
if ! command -v git >/dev/null 2>&1; then
  say "git isn't on PATH yet — pulling it into a temporary shell."
  note "(if this hangs, check your network connection first)"
  nix-shell -p git --run true
fi
note "✓ git available"
say "Network check:"
if curl -fsS --max-time 5 https://github.com >/dev/null 2>&1; then
  note "✓ can reach github.com"
else
  warn "can't reach github.com — fix networking before continuing"
  exit 1
fi
pause "Preflight looks good. Press Enter to continue."

# ── Stage 2: clone the repo ─────────────────────────────────────────────────
stage "Clone the config"
if [[ -d "$REPO_DIR/.git" ]]; then
  note "Repo already cloned at $REPO_DIR — pulling latest main instead."
  git -C "$REPO_DIR" fetch origin
  git -C "$REPO_DIR" checkout main
  git -C "$REPO_DIR" pull --ff-only origin main
else
  say "Cloning $REPO_URL"
  git clone "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"
note "✓ working in $REPO_DIR on branch $(git rev-parse --abbrev-ref HEAD)"
pause "Press Enter to continue."

# ── Stage 3: discover and confirm the real disk device ──────────────────────
stage "Confirm the disk device (DESTRUCTIVE — read carefully)"
say "hosts/${HOST}/_disko.nix currently assumes /dev/nvme0n1 (a placeholder,"
say "never confirmed against this physical machine). Let's check."
say ""
say "All disks on this machine:"
lsblk -d -o NAME,SIZE,MODEL | sed 's/^/    /'
say ""
say "Full layout (so you can see if anything is already mounted):"
lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | sed 's/^/    /'
say ""
warn "The device you confirm next will be COMPLETELY WIPED in a later stage."
warn "This is a full-wipe, single-NVMe install — no dual-boot, no undo."
ask DISK_DEVICE "Full path to ${HOST}'s NVMe drive (e.g. /dev/nvme0n1):"
say ""
warn "About to configure disko to wipe ${BOLD}${DISK_DEVICE}${RESET}${YELLOW} when you run it."
if ! confirm "Type the confirmation below only if you're certain this is correct"; then
  say "Aborted — re-run the script when you've confirmed the right device."
  exit 1
fi
say "Last check — type the device path again to confirm:"
ask DISK_DEVICE_CONFIRM "Re-type ${DISK_DEVICE} exactly:"
if [[ "$DISK_DEVICE" != "$DISK_DEVICE_CONFIRM" ]]; then
  warn "Those didn't match. Re-run the script and try again — nothing was changed."
  exit 1
fi
sed -i "s|device = \"/dev/nvme0n1\";|device = \"${DISK_DEVICE}\";|" "hosts/${HOST}/_disko.nix"
note "✓ hosts/${HOST}/_disko.nix updated"
pause "Press Enter to continue."

# ── Stage 4: discover and confirm PCI bus IDs for the hybrid GPU ────────────
stage "Confirm GPU PCI bus IDs"
if ! grep -q 'amdgpuBusId = "PCI:5:0:0"' "hosts/${HOST}/default.nix" 2>/dev/null; then
  say "hosts/${HOST}/default.nix doesn't declare the hybrid-GPU PRIME bus-ID"
  say "options (that pattern is specific to mast's AMD+NVIDIA Optimus laptop setup)."
  note "✓ nothing to do here for ${HOST} — skipping"
  pause "Press Enter to continue."
else
say "hosts/${HOST}/default.nix has placeholder PCI bus IDs for the AMD iGPU"
say "(Vega, built into the Ryzen 9 4900HS) and the NVIDIA dGPU (RTX 2060 Max-Q)."
say ""
say "GPU devices on this machine:"
lspci -nn | grep -E 'VGA|3D' | sed 's/^/    /'
say ""
say "Reading a PCI address into NVIDIA's PCI:bus:device:function format:"
say "  lspci shows e.g. '01:00.0' — that's bus=01, device=00, function=0, ALL IN HEX."
say "  NVIDIA's busId format wants the BUS number in DECIMAL. For low bus numbers"
say "  (00-09) hex and decimal look identical, so this is easy to miss — but if"
say "  lspci shows bus '0a', that's decimal 10, not literal \"0a\"."
say "  Example: lspci '05:00.0' → PCI:5:0:0.  lspci '0a:00.0' → PCI:10:0:0."
say ""
step "From the list above, identify which line is the AMD (Vega/Radeon) device"
step "and which is the NVIDIA (RTX 2060) device — don't mix them up."
ask AMD_BUS_HEX "AMD GPU's lspci bus number (the part before the colon, e.g. 05):"
ask AMD_DEV_HEX "AMD GPU's device number (between colon and dot, usually 00):"
ask NVIDIA_BUS_HEX "NVIDIA GPU's lspci bus number (e.g. 01):"
ask NVIDIA_DEV_HEX "NVIDIA GPU's device number (usually 00):"
AMD_BUS=$((16#${AMD_BUS_HEX}))
AMD_DEV=$((16#${AMD_DEV_HEX}))
NVIDIA_BUS=$((16#${NVIDIA_BUS_HEX}))
NVIDIA_DEV=$((16#${NVIDIA_DEV_HEX}))
AMD_BUS_ID="PCI:${AMD_BUS}:${AMD_DEV}:0"
NVIDIA_BUS_ID="PCI:${NVIDIA_BUS}:${NVIDIA_DEV}:0"
say ""
note "Computed: amdgpuBusId  = ${AMD_BUS_ID}"
note "Computed: nvidiaBusId = ${NVIDIA_BUS_ID}"
if ! confirm "Do these look right?"; then
  say "Aborted — re-run and re-check the lspci output above."
  exit 1
fi
sed -i "s|amdgpuBusId = \"PCI:5:0:0\";|amdgpuBusId = \"${AMD_BUS_ID}\";|" "hosts/${HOST}/default.nix"
sed -i "s|nvidiaBusId = \"PCI:1:0:0\";|nvidiaBusId = \"${NVIDIA_BUS_ID}\";|" "hosts/${HOST}/default.nix"
note "✓ hosts/${HOST}/default.nix updated"
pause "Press Enter to continue."
fi

# ── Stage 5: review before touching the disk ────────────────────────────────
stage "Review changes before anything destructive"
say "Diff of what's about to be used to partition and configure this machine:"
say ""
git diff -- "hosts/${HOST}/_disko.nix" "hosts/${HOST}/default.nix" | sed 's/^/    /'
say ""
warn "Next stage runs disko and WIPES ${DISK_DEVICE}. There is no undo past this point."
if ! confirm "Everything above looks correct — proceed to partitioning?"; then
  say "Stopped before touching the disk. Fix the files by hand if needed, then re-run."
  exit 1
fi

# ── Stage 6: partition and format via disko ─────────────────────────────────
stage "Partition and format (disko)"
warn "WIPING ${DISK_DEVICE} now."
say "disko wraps the root partition in LUKS — you'll be prompted for a passphrase"
say "in a moment. Pick one you'll actually remember: you'll type it on every boot."
pause "Press Enter to start disko."
sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- \
  --mode disko "./hosts/${HOST}/_disko.nix"
note "✓ disko finished — filesystems should now be mounted under /mnt"
mount | grep -E '/mnt(\s|$)' | sed 's/^/    /' || warn "nothing mounted at /mnt — something went wrong, stop and investigate."
pause "Confirmed the mounts above look right? Press Enter to continue."

# ── Stage 7: real hardware-configuration.nix ────────────────────────────────
stage "Generate hardware-configuration.nix"
say "disko already declared filesystems, so we skip that part of the generic scan."
sudo nixos-generate-config --no-filesystems --root /mnt
sudo cp /mnt/etc/nixos/hardware-configuration.nix "hosts/${HOST}/hardware-configuration.nix"
sudo chown "$(id -u):$(id -g)" "hosts/${HOST}/hardware-configuration.nix"
if ! grep -q "hardware-configuration.nix" "hosts/${HOST}/default.nix"; then
  sed -i "s|./_disko.nix|./_disko.nix\n        ./hardware-configuration.nix|" "hosts/${HOST}/default.nix"
  note "✓ added ./hardware-configuration.nix to hosts/${HOST}/default.nix imports"
fi
if grep -q "hardware.cpu.amd.updateMicrocode" "hosts/${HOST}/hardware-configuration.nix"; then
  note "✓ AMD microcode updates already configured"
else
  warn "hardware-configuration.nix doesn't set hardware.cpu.amd.updateMicrocode."
  say "Consider adding this line inside hosts/${HOST}/hardware-configuration.nix's config:"
  say '  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;'
  pause "Edit it now in another terminal if you want, then press Enter to continue."
fi
pause "Press Enter to continue."

# ── Stage 8: commit the real hardware values ────────────────────────────────
stage "Commit real hardware values (new branch, not main)"
say "The live installer has no git identity and almost certainly no GitHub"
say "credentials — that's expected here, not an error. This stage commits"
say "locally either way; push/PR are attempted but skipped gracefully if they"
say "fail. If they do, just relay the values below back wherever you normally"
say "push from (they're printed again at the end)."
if [[ -z "$(git config user.email 2>/dev/null)" ]]; then
  git config user.email "derricksouthworth@gmail.com"
  git config user.name "Derrick Southworth"
  note "✓ set a local (repo-only) git identity for this commit"
fi
BRANCH="${HOST}-hardware-values"
# Safe to re-run: an earlier attempt (e.g. one that failed later in this same
# stage) may have already created this branch.
if git rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
  git checkout "$BRANCH"
  note "✓ switched to existing branch $BRANCH (from an earlier attempt)"
else
  git checkout -b "$BRANCH"
fi
git add "hosts/${HOST}/_disko.nix" "hosts/${HOST}/default.nix" "hosts/${HOST}/hardware-configuration.nix"
if git commit -m "$(cat <<EOF
Add real hardware values for ${HOST}

- disk device: ${DISK_DEVICE}
- GPU PCI bus IDs: amd=${AMD_BUS_ID} nvidia=${NVIDIA_BUS_ID}
- generated hardware-configuration.nix (nixos-generate-config --no-filesystems)
EOF
)"; then
  note "✓ committed"
else
  note "nothing new to commit — already committed on an earlier attempt"
fi
if git push -u origin "$BRANCH" 2>/dev/null; then
  note "✓ pushed $BRANCH"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh pr create --fill --base main --head "$BRANCH" || warn "PR creation failed — open one by hand later"
  else
    SKIPPED+=("open a PR for branch $BRANCH (gh not available/authenticated here)")
    warn "gh not available here — open a PR for $BRANCH from another machine later"
  fi
else
  SKIPPED+=("push branch $BRANCH (no network/auth here) — relay these values to wherever you do have push access: device=${DISK_DEVICE} amdgpuBusId=${AMD_BUS_ID} nvidiaBusId=${NVIDIA_BUS_ID}, plus this repo's hosts/${HOST}/hardware-configuration.nix")
  warn "couldn't push $BRANCH right now — that's expected on a live installer, see the summary at the end"
fi
pause "Press Enter to continue."

# ── Stage 9: install ─────────────────────────────────────────────────────────
stage "Install"
say "This builds the full system closure and installs it to /mnt. Takes a while —"
say "make sure ${HOST} stays powered and on network throughout."
pause "Press Enter to start nixos-install."
sudo nixos-install --flake ".#${HOST}"
note "✓ nixos-install finished"

# ── Stage 10: set a login password ──────────────────────────────────────────
stage "Set a login password"
say "nixos-install just prompted (or will prompt) for a root password."
say "The 'ds' user account itself has no password set by the config — set one now"
say "so you can actually log in after reboot:"
step "sudo nixos-enter --root /mnt -c 'passwd ds'"
pause "Run that in another terminal now if you haven't, then press Enter to continue."

# ── Stage 11: reboot ─────────────────────────────────────────────────────────
stage "Reboot into the new install"
say "Remove the USB installer before rebooting."
if confirm "Ready to reboot now?"; then
  sudo reboot
else
  say "Skipping reboot — run 'sudo reboot' yourself when ready."
fi
say ""
say "After reboot, verify:"
step "LUKS passphrase prompt appears before boot continues"
step "Ly login screen loads"
step "sudo -i, then: mount | grep persist   (confirms /persist mounted — neededForBoot worked)"

finish
